### PR TITLE
Probably a fix

### PR DESCRIPTION
**Pull request by mbavaro**

### CODE REVIEW

**Comment by martin-swift** [comment]
Definitely.  I was wondering how that compiled; seems like nothing in the library itself is using it. 
Can you delete the useless comments while you at it?  (i.e. /* __cplusplus */)

**Comment by mbavaro** [comment]
Indeed, no source file includes this..

**Comment by martin-swift** [comment]
How did you find it?  is something in LSNP including it?

**Comment by mbavaro** [comment]
yes, I am trying to integrate it

**Pull request merged**
