### PR TITLE
Remove libsbp components from libswiftnav

### PR DESCRIPTION
**Pull request by mfine**
Remove the libsbp components from libswiftnav:

+ remove sbp's `crc16_ccitt` functionality
+ remove sbp, sbp_messages, sbp_utils
+ remove sbp_generate
+ remove sbp tests

This will be a standalone libswiftnav library to complement libsbp.

/cc @mookerji

### CODE REVIEW

**Comment by mookerji** [comment]
Uh.

**Comment by mookerji** [comment]
Good to test.

**Comment by mookerji** [comment]
ok to test

**Comment by mookerji** [comment]
Add to whitelist

**Comment by mookerji** [comment]
ok to test

**Comment by fnoble** [comment]
add to whitelist

**Comment by mfine** [comment]
Going to rebase this - then should be good to merge.

**Comment by mookerji** [comment]
This looks good. But needs to be staged with making the libsbp repo public.

**Comment by mfine** [comment]
Rebased and should be ready to go and merge.

**Pull request merged**
