### PR TITLE
Remove struct packing

### PR DESCRIPTION
**Pull request by mfine**
Don't use the packing attributes on the structs.

### CODE REVIEW

**Comment by mfine** [comment]
This is generating errors in gcc 9 with `-Werror=address-of-packed-member`

**Review by RReichert — APPROVED** [review]
LGTM. I believe this won't cause any issues since `gps_time_t` is already packed and `gnss_solution` isn't being `memcpy`'ed directly so there shouldn't be any issues with ABI being changed from this it seems.

**Review by jbangelo — APPROVED** [review]
This will change the ABI I think, since the packing attribute also removes the tail padding. Without any hard data it's a bit of a toss up in my opinion as too if this will have a positive or negative impact on overall performance. On the one hand it'll increase memory usage somewhat due to the added padding, but on the other hand the generated code accessing the members of this struct should be far simpler since the compiler doesn't have to compensate for potentially misaligned memory accesses (though I think that'll realistically only impact 32-bit ARM targets).

In any case I'm in favor of not packing structs unless absolutely necessary.

**Comment by jbangelo** [comment]
Demonstration that the size of the struct is effected by the packed attribute, and how the member access is complicated on ARM: https://godbolt.org/z/6sWx4W

**Comment by woodfell** [comment]
I haven't dug into it, but it looks like this change is causing some failures in starling https://github.com/swift-nav/starling/pull/4195

**Pull request merged**
