### PR TITLE
Experimental change to select shortest pseudo range for ordinal satellite

### PR DESCRIPTION
**Pull request by cturvey**
Modified calc_navigation_measurement_() to select the shortest path satellite for the ordinal satellite.

Current code picks minimum ToW (earlier) for dispatch time of signal vs current ToW at receiver. Should perhaps be the minimum delta in this context, not min/earliest time. This results in it picking the furthest satellite, lowest, with the worst signal path, and also prone to fade in/out. The observation (Ken) is that the RTK solution jumps in these cases, and you are also likely to see the biggest change in receiver clock drift/bias, which I'd otherwise expect to have a reasonably consistent rate-of-change. Haven't dug deep enough to see where receiver drift/bias are fixed, or if they are filtered.

The shortest path would tend to favour the highest elevation, clearest view satellite to be selected as the ordinal satellite, ie the one with the 2298000000 arbitrary measurement. This is the only place this constant is utilized.

-Clive

### CODE REVIEW

**Comment by fnoble** [comment]
ok to test

**Comment by fnoble** [comment]
Thanks Clive!

**Comment by cturvey** [comment]
No problem.

Where about in the code should I look for the fixing of the receivers clock
drift/bias? Does it remember or filter this epoch to epoch? Does it keep a
running value for clock drift, and does it slew it periodically?

**Comment by fnoble** [comment]
We don't filter or store the clock drift right now as we currently don't have that much use for it. You might be able to take a look at the `clock_offset` and `clock_bias` members of the `gnss_solution` output by `calc_PVT`. They contain the offset between the assumed clock implied by the choice of reference and GPS time, and the clock frequency bias.

**Comment by meee1** [comment]
ive added another pull request that I believe is more accurate than this one.

**Comment by fnoble** [comment]
A derivative of this was merged in #138.

**Pull request closed without merging**
