### PR TITLE
(syntax, doxygen comment format) checking

### PR DESCRIPTION
**Pull request by kovach**
- crappy script to run modified checkpatch.pl on src/.  cmake target to run it (make checkpatch)
- target that diffs doxygen warning output against file of allowed warnings (currently empty) (make check-doxygen)
- combined target (make check-style)
- ran uncrustify on source (~2k lines changed), manually fixed some issues

- checkpatch gives erroneous errors for ephemeris.c

- using checkpatch gives something over just diffing uncrustify, because (?) uncrustify can't 
  - fix parameter lists that should be (void)
  - remove trailing whitespace

- issue:
There are some outstanding libswiftnav pull requests that may have a large merge conflict with this

### CODE REVIEW

**Comment by kovach** [comment]
need to modify diff-cover to only consider `git diff --cached`

**Comment by kovach** [comment]
retest this please

**Comment by kovach** [comment]
retest this please

**Comment by scottswift** [comment]
TODO merge uncrustify commit

**Comment by ljbade** [comment]
@scottswift What is needed to get this ready for merge?

**Comment by scottswift** [comment]
i'll take a look at this tomorrow, but I think we should just rerun uncrustify on the current master and merge it if there aren't any major PRs that it will conflict with

**Comment by ljbade** [comment]
@scottswift great!

**Pull request closed without merging**
