### PR TITLE
implement alias_detect_reinit()

### PR DESCRIPTION
**Pull request by jacobmcnamee**

### CODE REVIEW

**Comment by ljbade** [comment]
@jacobmcnamee Is this ready for review?

**Comment by jacobmcnamee** [comment]
yes, "review"

**Comment by ljbade** [comment]
Code looks fine to me. But I don't really understand what this does.

@fnoble Perhaps you should review?

**Comment by jacobmcnamee** [comment]
I just wanted a reinit() function analogous to filter retune() for use in https://github.com/swift-nav/piksi_firmware/pull/580. That change configures / reconfigures alias detection when the integration period changes.

**Comment by ljbade** [comment]
Ah OK now I understand. Looks good so merging.

**Pull request merged**
