### PR TITLE
Stop if target already defined.

### PR DESCRIPTION
**Pull request by martin-swift**

### CODE REVIEW

**Comment by martin-swift** [comment]
@woodfell - so this is essentially the core of what I need.  (I'll probably want some more stuff, like detecting when the commit is different from the "native" one.)

**Comment by martin-swift** [comment]
I think we might need both this and your FindDependency, no?  sounds like your find dependency is somewhat orthogonal to this.

**Comment by jbangelo** [comment]
Does this need to be in libswiftnav? In my view it makes more sense to push the responsibility of checking for multiple definitions of the `swiftnav` target up to the projects including libswiftnav. Starling/orion/whatever else would need to conditionally use `add_subdirectory()`.

**Comment by martin-swift** [comment]
I am not in favor of that approach, because now the higher levels need to know what submodules add which targets and what their names are.  The orion model is the upper levels should not worry about what the submodules are doing for their dependencies. Think of it as a header guard - each file is responsible for making sure it doesn't get added twice.   Moreover, I intend to add machinery to create a manifest (@benjamin0 @mfine) that lists which submodules were added and what their git SHA is (and also which ones weren't, so we can flag inconsistent SHAs).  I'm waiting for @woodfell to merge his SetupDependency.cmake files so we're not re-inventing the wheel and we can have some kind of unification of functionality.

**Comment by woodfell** [comment]
This information is already at the higher level, the project above needs to know the target name so it can link against it.

I'm still working on trying to get this to work in a generic way isn't easy, and managing a tree where the same project is included multiple times on different branches is a massive headache and very time consuming to sort out.

**Comment by martin-swift** [comment]
that information only leaks up one level.  For example, nothing in orion-engine knows anything about libsbp or libswiftnav.  Orion knows nothing about starling.  This way, when we change starling to pvt-engine, etc. orion doesn't care.

**Comment by woodfell** [comment]
That's not an information leak, it's an essential part of the build process. If it went any higher it might be considered a leak, but even that is debatable. In any case, SetupDependency should cover all the use cases, an include guard is then really only needed to protect against someone using add_subdirectory without any extra checks

**Comment by martin-swift** [comment]
Semantics; each layer only needs to know about what it directly depends on.  That's abstraction.  I get there are different models out there (like the package manager model, but this is the one orion is built around).  If we want to move away from that, that's a major architecture decision for @anth-cole and @mfine.

Right - this is exactly why I'm waiting to see how SetupDependency turns out so we can align behind one method instead instead of making redundant (or worse - conflicting) CMake.  But no rush today, per se.  Ben has requested that I work another ticket for now.

**Comment by jbangelo** [comment]
@martin-swift I think we're all advocating for the same thing. Just Matt and myself are suggesting that the project including a dependency should check if the needed targets are already defined before calling `add_subdirectory()` instead of the dependency checking if its targets are already defined. Starling (and maybe orion-proto?) being changed instead of the dependencies (libswiftnav and libsbp).

**Comment by martin-swift** [comment]
Ok, sell me on why that's better.  Because let's image you have a project called Widgets.  It has submodules A and B.   "A" provides targets foo and bar, and B provides yar and baz.  Now Widgets has to know that foo and bar come from A and yar and baz come from B.  So what happens when you decide that actually bar belongs in B with baz and yar belongs in A with foo?  If each submodule guards itself against multiple inclusion, Widgets doesn't have to care about any of that.  Zero pull requests to Widgets for that change.  And in its most minimal form, that's 3 lines of CMake, so I also don't understand why this is hard.  This paradigm has been used to great effect in C/C++.

**Comment by martin-swift** [comment]
If we roll the with the header file analogy, think of how unworkable that would be if the includer of a header file had to check all the defines in a header file to determine if they had already been defined or not.  Looks like a very applicable analogy, no?

**Comment by martin-swift** [comment]
Just read @woodfell 's document in full - your statement seems to be at odds with what he expressed in his document:
```
Each top level CMakeLists.txt would need to protect against multiple inclusion, a construct similar C header file include guards would suffice in the first instance but something more sophisticated might be required in the future
```
So do we have alignment on this?

**Comment by jbangelo** [comment]
Matt will have to speak for himself, I shouldn't have earlier. I think I've got two slightly different model of how this all works in my head. Maybe have a short chat face to face tomorrow, instead of posting long comments?

**Comment by martin-swift** [comment]
:+1: Definitely. (also, they're not that long, and it's kinda what you have to do when we are remote...)

**Comment by woodfell** [comment]
Closing since this is very out of date. Issues have been solved by dependency system implemented in other tickets.

**Pull request closed without merging**
