### PR TITLE
Extend me_gnss_signal_t with me_code_t

### PR DESCRIPTION
**Pull request by adel-mamin**
Issue: https://swift-nav.atlassian.net/browse/EX-354

### CODE REVIEW

**Comment by adel-mamin** [comment]
> I'd almost say this ME_* type should live outside of libswiftnav...

The PR uses ME_* enums in `me_gnss_signal`, which is declared in `signal.h`. What would be the better place for the ME_* type?

**Comment by mbavaro** [comment]
I had in mind a libswiftnav agnostic of ME code, and a translation layer just at the point when we produce observations, for which ME needs to know about LSN code_t but the contrary isn't necessarily true. I'd give it a spin if I'd have time.. maybe this weekend

**Comment by mbavaro** [comment]
I mean.. I am wondering about the benefits of having the `ME_CODE_` enum, especially in ME code where all the unsupported signals have already been pruned from switch and conditional statements..

**Comment by adel-mamin** [comment]
> I mean.. I am wondering about the benefits of having the ME_CODE_ enum, especially in ME code where all the unsupported signals have already been pruned from switch and conditional statements..

I have the same concerns. The benefits of having it implemented this way do not look obvious to me.

**Comment by adel-mamin** [comment]
@mbavaro 
> I'd say that me_gnss_signal_t could live in piksi_firmware_private entirely.

I added 
https://github.com/swift-nav/libswiftnav/pull/50
https://github.com/swift-nav/starling/pull/2053
https://github.com/swift-nav/piksi_firmware_private/pull/2621
to move `me_gnss_signal_t` declaration to PFW.

**Comment by adel-mamin** [comment]
@mbavaro Do you see any value in the PR? Or should I close it?

FYI, I have merged these PR so far, which are in the similar area:
https://github.com/swift-nav/piksi_firmware_private/pull/2621
https://github.com/swift-nav/libswiftnav/pull/50
https://github.com/swift-nav/starling/pull/2053
https://github.com/swift-nav/libswiftnav/pull/48

**Comment by mbavaro** [comment]
I think those give us a chance of reshaping `me_gnss_signal_t` in the future, if needed. I think this PR could be closed.

**Comment by adel-mamin** [comment]
Agree. Closing.

**Pull request closed without merging**
