### PR TITLE
Use time pointers in time functions

### PR DESCRIPTION
**Pull request by ljbade**
To be merged after https://github.com/swift-nav/libswiftnav/pull/262

I have implemented a number of TODOs from `time.c`.

They are
- use a pointer for `gps_time_t` in functions that take one.
- in place normalisation via pointer instead of a return value

### CODE REVIEW

**Comment by ljbade** [comment]
@mookerji Can you help me with updating the Python bindings?

**Comment by mookerji** [comment]
@ljbade yeah, dude, probably in the morning though.

ZZzzzzZZZZzzzzzzzz......

**Comment by mookerji** [comment]
Yeah, so the places that previous passed by value should now pass by reference. In the following, places with `time._thisptr` should now be `&time._thisptr`. See: 

```
swiftnav/ephemeris.pyx-49-  def calc_sat_state(self, GpsTime time):
swiftnav/ephemeris.pyx-50-    cdef np.ndarray[np.double_t, ndim=1, mode="c"] pos = np.array([0,0,0], dtype=np.double)
swiftnav/ephemeris.pyx-51-    cdef np.ndarray[np.double_t, ndim=1, mode="c"] vel = np.array([0,0,0], dtype=np.double)
swiftnav/ephemeris.pyx-52-    cdef double clock_err, clock_rate_err
swiftnav/ephemeris.pyx:53:    calc_sat_state(&self._thisptr, time._thisptr, &pos[0], &vel[0], &clock_err, &clock_rate_err)
swiftnav/ephemeris.pyx-54-    return (pos, vel, clock_err, clock_rate_err)
swiftnav/ephemeris.pyx-55-
swiftnav/ephemeris.pyx-56-  def good(self, GpsTime time):
swiftnav/ephemeris.pyx:57:    return ephemeris_good(&self._thisptr, time._thisptr)
```

**Comment by ljbade** [comment]
@mookerji thanks I will take a crack today

**Comment by ljbade** [comment]
@swift-nav/firmware Ready for review

**Comment by jacobmcnamee** [comment]
Pointer changes look fine. I'm not sure what the makefile changes are or if they are intended.

**Comment by ljbade** [comment]
@jacobmcnamee You are right "Showing  29 changed files  with 29,939 additions and 1,392 deletions."

Something in git went wrong.

**Comment by ljbade** [comment]
Oh I see clapack uses self modifyng makefiles! What a stupid idea. I guess you have to be careful about running `make` in `build/` before you `git commit -a`.

**Comment by ljbade** [comment]
@jacobmcnamee I fixed up the makefiles

**Pull request merged**
