### PR TITLE
PVT altitude sanity check: halfway to the moon isn't very sane

### PR DESCRIPTION
**Pull request by henryhallam**
Closes swift-nav/piksi_firmware#339

### CODE REVIEW

**Comment by fnoble** [comment]
Hmm.. `soln_llh` is in meters internally so this should be correct. Are you sure you verified the bug?

**Comment by henryhallam** [comment]
@fnoble per [pvt.h](https://github.com/swift-nav/libswiftnav/blob/master/include/libswiftnav/pvt.h#L36) it's in meters.  What I saw was very consistent with the solution being dropped below -1 m.  I feel like putting it on the signal simulator would be a waste of time, but I'll do it if you want.

**Comment by henryhallam** [comment]
Derp, I mean yes I see what you mean. Hmm.

**Comment by henryhallam** [comment]
..in which case 1e8 seems too high for the upper limit, given that's halfway to the moon.

**Comment by henryhallam** [comment]
We saw Piksi outputting solutions with altitude in the ~ -10 m range, so clearly this was bogus as originally filed.

**Pull request merged**
