### PR TITLE
Update cmake submodule pointer [ESD-1410]

### PR DESCRIPTION
**Pull request by wurmmi**
Just update the cmake submodule to latest master.

### CODE REVIEW

**Comment by wurmmi** [comment]
Yes, this is a known issue. It appeared after https://github.com/swift-nav/cmake/commit/ce342d7d2ca4cebb4a65ef5067eddc6eb5b5494f was merged.
Actually, @woodfell could you take a look at that?

**Comment by mbavaro** [comment]
changed 
https://github.com/swift-nav/cmake/blob/master/ClangTidy.cmake#L275
to
```
    message(STATUS "$$$$ ${x_EXTRA_ARGS}")
```
and does not break.. the current doesn't look like an error condition to me?

**Comment by woodfell** [comment]
> mmm... gives me this
> 
> ```
> -- Using /usr/bin/clang-tidy-6.0
> CMake Warning at cmake/common/ClangTidy.cmake:275 (message):
>   $$$$
> Call Stack (most recent call first):
>   CMakeLists.txt:29 (swift_setup_clang_tidy)
> ```
> 
> is it OK?

Ah, my bad. That was a bit of debugging that got left in

**Comment by wurmmi** [comment]
I'll put up a PR and ping you on it.

**Pull request merged**
