### PR TITLE
Coveralls code coverage and Travis updates

### PR DESCRIPTION
**Pull request by fnoble**

### CODE REVIEW

**Comment by mfine** [comment]
Needs a badge on the README.:

```text
[![Coverage status][libswiftnav-coveralls-img]][libswiftnav-coveralls]

[libswiftnav-coveralls-img]: https://coveralls.io/repos/swift-nav/libswiftnav/badge.svg?branch=master&service=github
[libswiftnav-coveralls]: https://coveralls.io/github/swift-nav/libswiftnav?branch=master
```

**Comment by fnoble** [comment]
@mfine : its already in there

**Comment by mfine** [comment]
Sorry, missed that - nice!

**Comment by fnoble** [comment]
trying to get it to work on the containerized infrastructure - its a pita

**Comment by mookerji** [comment]
Looks good to me!

**Pull request merged**
