### PR TITLE
Add preliminary support for decoding BGD (Broadcast Group Delay) from

### PR DESCRIPTION
**Pull request by pgrgich**
GAL ephemerides

Set valid to 0 if health status does not report that signal is ok

Fix tests

Commit clang-format-diff-check

Always set eph->valid

### CODE REVIEW

**Comment by silverjam** [comment]
Is there a master commit(s) that this was back ported from?

**Comment by silverjam** [comment]
Note, this is backported from https://github.com/swift-nav/libswiftnav/compare/8f8c2e2e42e863569dc5f091d781550afc9b4311...63c474a8e3e0bbae5712488b54cc0ad49e09d75c

**Comment by nejla-m** [comment]
Hotfix was approved, however let's not merge until we have the GTT results

**Comment by pgrgich** [comment]
Already merged onto master and will therefore be in v1.2 -> no need to worry about v1.1 any more.

**Pull request merged**
