### PR TITLE
Add `code_to_str()`

### PR DESCRIPTION
**Pull request by mbavaro**
Does what it's supposed to..

### CODE REVIEW

**Comment by mbavaro** [comment]
@martin-swift does this hurt your feelings?

**Comment by martin-swift** [comment]
Might be totally reasonable, except what problem is this solving?

**Comment by mbavaro** [comment]
I just need something to associate a `code_t` to a string, `sat_code_to_string()` does not cut it, nor `sid_to_string()` or `mesid_to_string()`.

**Comment by mbavaro** [comment]
Thanks Martin, mergin away

**Pull request merged**
